//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 07:53:22 PM EDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ws.example.com/")
package com.example.ws;
